#!/usr/bin/env ruby
#
# Make individual bin executable system-wide.
#
# This means the binary will be added to
# `/usr/local/bin`, which is in your `$PATH`
# by default.
# 
# Anything in your `$PATH` is available from
# anywhere in your system.
# 
# USAGE:
#   $ ./show-off
#   # => Follow the script instructions
#   
# OS SUPPORT:
#   Linux and MacOS
#  
# SOURCE:
#   https://github.com/lsfernandes92/awesome-scripts/tree/main/public/bins/show-off/
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'gum'
end

require 'gum'

class ProcessBin
  USR_LOCAL_BIN_DIR = "/usr/local/bin"

  def initialize(path)
    @path = path
    @bin = path.split("/").last
  end

  def process
    make_executable
    symlink
  end

  private

  def make_executable
    Gum::Log.warn("💬 To make '#{@bin}' executable, sudo is required.")

    if proceed? && sudo_granted?
      Gum.spin("Loading...", spinner: :dot, command: "sleep 1")
      Gum::Log.info("✅ Bin '#{@bin}' is now executable!")
    else
      Gum::Log.error("❌ Failed to make '#{@bin}' executable")
      exit 1
    end
  end

  def proceed?
    Gum.confirm("Do you even trust this script? (𓁹‿ 𓁹)", default: true)
  end

  def sudo_granted?
    system("gum input --password --placeholder 'Please enter sudo password...' | sudo -S chmod +x #{@path}")
  end

  def symlink
    target = "#{USR_LOCAL_BIN_DIR}/#{@bin}"
    
    system("sudo rm -f #{target}")
    
    if system("sudo ln -s #{@path} #{target}")
      Gum.spin("Symlinking...", spinner: :dot, command: "sleep 1")
      Gum::Log.info("✅ Symlinked '#{@bin}' to #{USR_LOCAL_BIN_DIR}")
      Gum::Log.info("✅ Done! You may need to reload your terminal. ↻")
    else
      Gum::Log.error("❌ Failed to symlink '#{@bin}'")
      exit 1
    end
  end
end

def what_to_do
  Gum.choose(
    "✨ Show bin off (you’ll be prompted to select a bin file)",
    "🤔 What's a bin BTW?",
    "ℹ️ Are you lost?",
    "🚪 I'm out!",
    header: "💬 Let me guess...\n"
  )
end

def open_file_selector
  Gum.file("#{ENV['HOME']}", all: true)
end

def show_whats_bin_btw
  main = <<~MAIN
    # WHAT'S BIN BTW?

    _To make things easier, here,
    the terms **script**, **executable**,
    **bin** and **binary** mean the same 
    thing._

    These scripts aim to automate
    tasks and set shortcuts
    whether for productivity or fun. 
    
    They are like **executables**
    that you can run by calling
    the script name.  
  MAIN

  help_text = <<~HELP
    #{Gum.format(main, type: :markdown)}
  HELP

  Gum.pager(help_text, soft_wrap: true)
end

SCRIPT_NAME = Gum.style('./show-off', foreground: 1)
def show_help
  header = <<~HEADER
    # awesome@scripts > /bins > #{SCRIPT_NAME}
  HEADER
  main = <<~MAIN
    # WHAT THIS SCRIPT DO?
          It make individual bin executable system-wide.

          This means the binary will be added to
          `/usr/local/bin`, which is in your `$PATH`
          by default. 
          
          Anything in your `$PATH` is available from
          anywhere in your system.

    # OPTIONS:
          --help, -h          Show this help message

    # USAGE:
          $ ./show-off
          # => Follow the script instructions
    
    # OS SUPPORT:
          Linux and MacOS
    
    # SOURCE:
          https://github.com/lsfernandes92/awesome-scripts/tree/main/public/bins/show-off/
  MAIN

  help_text = <<~HELP
    #{Gum.format(header, type: :markdown)}
    #{Gum.format(main, type: :markdown)}
  HELP

  Gum.pager(help_text, soft_wrap: true)
end

if ARGV.include?('--help') || ARGV.include?('-h')
  show_help
  exit 0
end

while true
  case what_to_do
  when "🤔 What's a bin BTW?"
    show_whats_bin_btw
  when "ℹ️ Are you lost?"
    show_help
  when "🚪 I'm out!"
    Gum::Log.info("Goodbye then! 👋") 
    exit 1
  else
    bin_path = open_file_selector
    
    unless bin_path
      Gum::Log.error("❌ No binary selected")
      exit 1
    end

    ProcessBin.new(bin_path).process
  end
end
