#!/usr/bin/env ruby
#
# Outputs a random fun fact in your terminal
#
# When it gets run it simply outputs a 
# random fun fact in your terminal.
#
# OPTIONS:
#   --help, -h          Show this help message
#
# USAGE:
#   $ ./funfact
#   # => Outputs a random fun fact in your terminal
#
# OS SUPPORT:
#   Linux and MacOS
#  
# SOURCE:
#   https://github.com/lsfernandes92/awesome-scripts/tree/main/public/bins/funfact/
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'gum'
end

require 'json'
require 'gum'

USELESS_API_URL = "https://useless.dotenv.dev/api/random"
SCRIPT_NAME = Gum.style('./funfact', foreground: 1)

def show_help
  header = <<~HEADER
    # awesome@scripts > /bins > #{SCRIPT_NAME}
  HEADER
  main = <<~MAIN
    # WHAT THIS SCRIPT DO?
          Outputs a random fun fact in your terminal
        
          When it gets run it simply outputs a 
          random fun fact in your terminal.

    # OPTIONS:
          --help, -h          Show this help message

    # USAGE:
          $ ./funfact
          # => Outputs a random fun fact in your terminal
    
    # OS SUPPORT:
          Linux and MacOS
    
    # SOURCE:
          https://github.com/lsfernandes92/awesome-scripts/tree/main/public/bins/funfact/
  MAIN

  help_text = <<~HELP
    #{Gum.format(header, type: :markdown)}
    #{Gum.format(main, type: :markdown)}
  HELP
  
  Gum.pager(help_text, soft_wrap: true)
  exit 0
end

if ARGV.include?('--help') || ARGV.include?('-h')
  show_help
end

string_response = `curl #{USELESS_API_URL} 2>/dev/null`
hash_response = JSON.parse(string_response)
fact = hash_response.dig('fact')

Gum.spin("Fetching...", spinner: :dot) do
  puts Gum.style(
    "ᩭᘏᗢ ˎˊ˗#{fact} ᗢᘏᓗ",
    foreground: 2,
  )
end
